window.lyricsDatabase = {
  "what-did-you-do-yesterday": [
    { time: 6.54, text: "I went to the park" },
    { time: 8.18, text: "I played on the swing" },
    { time: 9.74, text: "I saw a red kite" },
    { time: 11.4, text: "It danced in the spring" },
    { time: 13.04, text: "I walked to the store" },
    { time: 14.68, text: "I bought one small snack" },
    { time: 16.0, text: "Then I ran back home" },
    { time: 17.74, text: "And I looked at my map" },
    { time: 19.6, text: "Tell me where you went" },
    { time: 21.24, text: "Tell me what you saw" },
    { time: 22.6, text: "Use the past tense words" },
    { time: 24.12, text: "That’s the golden law" },
    { time: 27.74, text: "What did you do yesterday?" },
    { time: 29.72, text: "What did you do yesterday?" },
    { time: 33.0, text: "I went, I saw, I played" },
    { time: 36.28, text: "I went, I saw, I played" },
    { time: 40.74, text: "What did you do yesterday?" },
    { time: 42.69, text: "What did you do yesterday?" },
    { time: 45.95, text: "At the park, at the store" },
    { time: 49.95, text: "At the zoo, by the door" },

    { time: 55.21, text: "I went to the zoo" },
    { time: 56.81, text: "I fed a giraffe" },
    { time: 58.43, text: "I took a big photo" },
    { time: 59.93, text: "And I laughed and laughed" },
    { time: 61.73, text: "I went to the library" },
    { time: 63.29, text: "I found a good book" },
    { time: 64.93, text: "I sat by the window" },
    { time: 66.43, text: "And had a long look" },
    { time: 68.29, text: "Tell me where you went" },
    { time: 69.91, text: "Tell me what you did" },
    { time: 71.13, text: "Past simple is easy" },
    { time: 72.81, text: "Let’s sing it, kids" },
    { time: 76.37, text: "What did you do yesterday?" },
    { time: 78.41, text: "What did you do yesterday?" },
    { time: 81.65, text: "I went, I saw, I played" },
    { time: 86.03, text: "I went, I saw, I played" },
    { time: 89.41, text: "What did you do yesterday?" },
    { time: 92.67, text: "What did you do yesterday?" },
    { time: 94.93, text: "At the park, at the store" },
    { time: 97.85, text: "At the zoo, by the door" },

    { time: 103.85, text: "I went to the school" },
    { time: 105.49, text: "I wrote on the board" },
    { time: 107.11, text: "I went to the café" },
    { time: 108.77, text: "And ordered a strawberry drink" },
    { time: 110.79, text: "I went to the museum" },
    { time: 112.41, text: "I looked at the art" },
    { time: 113.71, text: "Then I went home happy" },
    { time: 114.95, text: "With the places in my heart" },
    { time: 118.53, text: "What did you do yesterday?" },
    { time: 120.56, text: "What did you do yesterday?" },
    { time: 123.92, text: "I went, I saw, I played" },
    { time: 128.22, text: "I went, I saw, I played" },
    { time: 131.58, text: "What did you do yesterday?" },
    { time: 134.6, text: "What did you do yesterday?" },
    { time: 137.14, text: "At the park, at the store" },
    { time: 140.78, text: "At the zoo, by the door" },
    { time: 146.14, text: "What did you do yesterday?" },
    { time: 149.31, text: "What did you do yesterday?" },
    { time: 152.50, text: "I went, I saw, I played" },
    { time: 155.67, text: "I went, I saw, I played" },
  ],

  "fantastic-world-dance": [
    { time: 10.54, text: "WORLD TOUR" },

    { time: 18.13, text: "Got a map in my hand, got a ticket to ride," },
    { time: 21.72, text: "Got my friends all ready, everybody outside." },
    { time: 25.29, text: "We can travel farther, we can travel higher," },
    { time: 29.2, text: "Every new adventure makes us feel the fire." },

    { time: 33.03, text: "See a bigger city, see a brighter sky," },
    { time: 35.01, text: "Find a faster train as it rushes by." },
    { time: 36.94, text: "Every day is different, every day is new," },
    { time: 38.79, text: "Around the world with me and you!" },

    { time: 40.86, text: "He-e-e-ey!" },
    { time: 42.7, text: "Where do we go?" },
    { time: 44.55, text: "He-e-e-ey!" },
    { time: 46.33, text: "Nobody knows!" },

    { time: 48.25, text: "WOW!" },
    { time: 49.58, text: "FANTASTIC WORLD!" },
    { time: 52.03, text: "DANCE!" },
    { time: 52.85, text: "Around the world," },
    { time: 54.38, text: "Together we go!" },
    { time: 55.79, text: "WOW!" },
    { time: 57.04, text: "FANTASTIC WORLD!" },
    { time: 59.26, text: "DANCE!" },
    { time: 60.09, text: "The best adventure we know!" },

    { time: 70.37, text: "Higher than a mountain," },
    { time: 72.09, text: "Longer than a river," },
    { time: 73.81, text: "More exciting than before," },
    { time: 75.73, text: "And getting even bigger." },
    { time: 77.52, text: "See the deepest ocean," },
    { time: 78.61, text: "See the brightest light," },
    { time: 79.49, text: "Find the most amazing places" },
    { time: 81.05, text: "Every day and every night." },

    { time: 85.2, text: "He-e-e-ey!" },
    { time: 87.18, text: "Where do we go?" },
    { time: 88.98, text: "He-e-e-ey!" },
    { time: 90.78, text: "Nobody knows!" },

    { time: 92.7, text: "WOW!" },
    { time: 93.8, text: "FANTASTIC WORLD!" },
    { time: 96.18, text: "DANCE!" },
    { time: 97.09, text: "Around the world," },
    { time: 98.61, text: "Together we go!" },
    { time: 100.08, text: "WOW!" },
    { time: 101.12, text: "FANTASTIC WORLD!" },
    { time: 103.66, text: "DANCE!" },
    { time: 104.48, text: "The best adventure we know!" },

    { time: 114.57, text: "HEY HEY HEY HEY!" },
    { time: 116.56, text: "Higher mountains," },
    { time: 118.38, text: "Brighter skies! Brighter skies!" },
    { time: 120.21, text: "Bigger cities" },
    { time: 122.02, text: "Pass us by! Pass us by!" },
    { time: 123.88, text: "More exciting," },
    { time: 125.52, text: "More beautiful! More beautiful!" },
    { time: 127.42, text: "The best adventure in our lives!" },

    { time: 130.51, text: "WHOA-OH WOW!" },
    { time: 132.05, text: "FANTASTIC WORLD!" },
    { time: 134.91, text: "DANCE!" },
    { time: 135.7, text: "Around the world," },
    { time: 137.4, text: "Together we go!" },
    { time: 138.85, text: "WOW!" },
    { time: 140.02, text: "FANTASTIC WORLD!" },
    { time: 142.27, text: "DANCE!" },
    { time: 143.13, text: "The best adventure we know!" },
  ],

  "pizza-left-right": [
    { time: 2.44, text: "Anna's got a notebook," },
    { time: 3.62, text: "Ready with a plan." },
    { time: 4.8, text: "Winnie starts laughing," },
    { time: 5.92, text: "And everybody can!" },

    { time: 7.1, text: 'Alisa says, "Wait!"' },
    { time: 8.38, text: 'David says, "Go!"' },
    { time: 9.64, text: "Nobody knows" },
    { time: 10.56, text: "What's happening, bro!" },

    { time: 12.02, text: 'Max says, "Left!"' },
    { time: 13.2, text: 'Mark says, "Right!"' },
    { time: 14.54, text: 'Q says, "Pizza!"' },
    { time: 15.38, text: "And they dance all night!" },

    { time: 16.8, text: "Hey! Hey!" },
    { time: 18.32, text: "This is the coolest class!" },
    { time: 21.58, text: "Hey! Hey!" },
    { time: 23.08, text: "We're having fun so fast!" },

    { time: 26.5, text: "Anna!" },
    { time: 27.0, text: "Winnie!" },
    { time: 27.52, text: "Alisa!" },
    { time: 28.18, text: "David!" },
    { time: 28.8, text: "Max!" },
    { time: 29.41, text: "Mark!" },
    { time: 29.89, text: "And Q!" },

    { time: 31.41, text: "Everybody sing:" },
    { time: 32.45, text: '"That\'s what we do!"' },
    { time: 37.23, text: "That's what we do!" },
    { time: 42.03, text: "That's what we do!" },

    { time: 43.31, text: "Anna finds a pencil," },
    { time: 44.43, text: "Winnie finds two." },
    { time: 45.55, text: "Alisa finds a mystery," },
    { time: 46.83, text: "Q finds a shoe." },

    { time: 48.03, text: "David tells a story," },
    { time: 49.27, text: "Max starts to grin." },
    { time: 50.45, text: 'Mark says, "Let\'s go!"' },
    { time: 51.97, text: "And the trouble begins." },

    { time: 53.01, text: 'Max says, "Left!"' },
    { time: 54.03, text: 'Mark says, "Right!"' },
    { time: 55.19, text: 'Q says, "Pizza!"' },
    { time: 56.19, text: "And they dance all night." },

    { time: 57.61, text: "Hey! Hey!" },
    { time: 59.13, text: "This is the coolest class!" },
    { time: 62.43, text: "Hey! Hey!" },
    { time: 63.95, text: "We're having fun so fast!" },

    { time: 66.49, text: "Anna!" },
    { time: 67.81, text: "Winnie!" },
    { time: 68.33, text: "Alisa!" },
    { time: 69.01, text: "David!" },
    { time: 69.63, text: "Max!" },
    { time: 70.23, text: "Mark!" },
    { time: 70.71, text: "And Q!" },

    { time: 72.23, text: "Everybody sing:" },
    { time: 73.27, text: '"That\'s what we do!"' },
    { time: 78.05, text: "That's what we do!" },
    { time: 82.85, text: "That's what we do!" },

    { time: 84.11, text: "Who's got a pencil?" },
    { time: 85.27, text: "Who's got a pen?" },
    { time: 86.31, text: "Who's ready to do it" },
    { time: 87.55, text: "Again and again?" },
    { time: 88.94, text: "Everybody ready?" },

    { time: 90.23, text: "ONE!" },
    { time: 90.66, text: "TWO!" },
    { time: 91.23, text: "THREE!" },

    { time: 93.67, text: "Hey! Hey!" },
    { time: 95.16, text: "This is the coolest class!" },
    { time: 98.52, text: "Hey! Hey!" },
    { time: 99.96, text: "We're having fun so fast!" },

    { time: 102.52, text: "Anna!" },
    { time: 103.84, text: "Winnie!" },
    { time: 104.36, text: "Alisa!" },
    { time: 105.04, text: "David!" },
    { time: 105.66, text: "Max!" },
    { time: 106.24, text: "Mark!" },
    { time: 106.74, text: "And Q!" },

    { time: 108.26, text: "Everybody sing:" },
    { time: 109.3, text: '"That\'s what we do!"' },
    { time: 113.98, text: "That's what we do!" },
    { time: 118.71, text: "That's what we do!" },
  ],
};
